[project]
name = "sumanth-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.6.0",
    "jupytext>=1.19.5",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "opencv-python-headless>=5.0.0.93",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pytest>=9.1.1",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "streamlit>=1.64.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

